// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package webhooksdb

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Subscription struct {
	ID uuid.UUID `json:"id"`
}

type Webhook struct {
	ID             uuid.UUID       `json:"id"`
	SubscriptionID uuid.UUID       `json:"subscription_id"`
	CreatedAt      string          `json:"created_at"`
	AckedAt        sql.NullTime    `json:"acked_at"`
	Payload        json.RawMessage `json:"payload"`
}
